### ISSUE TITLE
feat. request: support NMM saves format

### ISSUE THREAD

**Issue by GoogleCodeExporter** [suloku/gcmm#10]
```
inject/extract saves from/to NMM saves used by diosmios
http://code.google.com/p/diosmios/

```

Original issue reported on code.google.com by `mantox...@gmail.com` on 13 Oct 2012 at 12:14

**Comment by angelbless** [comment]
Thxs for the update! I have some troubles with the software. I cant convert raw files to gci and when converting my gci dump of my GC memory card files to a raw file I 1) get a lower size file than the ones Im trying to replace in Nintendont and 2) when replacing and putting the .raw extension, the file gest corrupted while loading the game.

**Comment by suloku** [comment]
Closing this since no more memory and dios mios have been outdated by nintendont.
