### ISSUE TITLE
Same name/different case save files causing backup issues.

### ISSUE THREAD

**Issue by DakuTree** [suloku/gcmm#24]
Had two profiles on Timesplitters 2 with the same name, different case (DAKU & Daku (This being the newer one)).
On the backup menu, the filenames of both of these are different (4F-GTSE-DAKU.son & 4F-GTSE-Daku.son), but they return the same data. (Everything is the same as the oldest profile)
Doing a mass-backup caused the oldest profile to be backed up twice, and the newer one doesn't appear to be backed up at all.
Sadly found this all out after reformatting my card :cry:, meaning the newer save was lost.

I'm assuming this bug will also exist in any other game with multiple named profiles (Timesplitters 3 is the only one that comes to mind...).

**Comment by Antidote** [comment]
Looks like filenames aren't case insensitive, easy fix.

**Comment by Antidote** [comment]
Alright, try the change I just made in card.c for GCMM and see if that solves the problem:
https://github.com/devkitPro/libogc/pull/7

**Comment by DakuTree** [comment]
That seems to have fixed the issue. Thanks.

**Comment by Antidote** [comment]
No problem :D

**Comment by suloku** [comment]
I can't believe I wasn't subscribed to gcmm git notifications, I will update as soon as I can. Thank you very much for noticing + fix.

**Comment by Antidote** [comment]
You're welcome!
