### ISSUE TITLE
Request: Add Memory Card Dump/Restore via BBA, if possible

### ISSUE THREAD

**Issue by bytemedeep** [suloku/gcmm#26]
Hi.  Not sure if it's at all possible using PSO + broadband adapter, but it would be nice if GCMM would allow dumping/restoring of memory card saves to your PC through the broadband adapter (esp for people who don't have SD Gecko or SD memory card adapters).  I just thought if you can dump the game image to your PC through the BBA (and even stream them back to the GCN), then why not memory card saves, right? :)

**Comment by suloku** [comment]
There's ctr-gcs from back in the old days for pso+bba: http://www.gc-forever.com/forums/viewtopic.php?f=37&t=8&sid=e4c9512f3927bba7d7a51c061fe65aae

GCS 1.0a - CrowTRobo

I personally have no plans for it, nor the needed knowledge to implement any network related capabilities.
