### ISSUE TITLE
Large Memory Card Raw Restore Fails

### ISSUE THREAD

**Issue by xperia64** [suloku/gcmm#27]
I have a large 2043 block 128Mb card that I raw backed up. I tried to restore it recently and it failed at block 1024 which seems a little suspicious. To restore my saves I had to format the card, extract all of the GCI's with dolphin and batch import them back with GCMM.

**Comment by suloku** [comment]
This is strange, last time I checked with my 2043 block card it worked fine.
Unfortunately, my current occupations won't allow me to look into this matter. But what I can do is test your raw image with my 2043 block card if you upload it to confirm the issue.
Also, were you using latest 1.4e release?

**Comment by xperia64** [comment]
I'm using 1.4d since that's the only compiled version I could easily find.

**Comment by suloku** [comment]
Then using 1.4d or 1.4e shouldn't make a difference for your problem (btw the releases are all here at github releases page)

**Comment by elchhome** [comment]
I have the same problem and tested two different brands of 128mb cards (eaxus/bigben).
Restoring the raw image stops at 1210.
The old release 1.3 does work while the new one 1.4f does not.

**Comment by suloku** [comment]
Just tested raw backup and restore on a 2048 block memory card on version 1.5. I had no problems.
Is this still an issue for someone?

**Comment by rayfoster14** [comment]
Hi,
I am also expecting this problem. On v1.5 a raw import will fail to write at Block 0, and on V1.4f it will fail to write at block 1024 consistently. Is there a version with a higher compatibility for 2043 block cards?

**Comment by suloku** [comment]
Can you test on 1.3? I'll retest my 2024 and 2043 block cards anyways, see if I can reproduce the problem

**Comment by rayfoster14** [comment]
Hi, so I gave 1.3 a go. It did manage to write 2043 blocks to my memory card, however on closer inspection all of the save data was corrupted. I purchased a new 128MB card to test this out on in case my memory card was faulty but all of the same results from before on v1.4f and v1.5 applied.

**Comment by rayfoster14** [comment]
Sure no problem, can I send it over via email?

**Comment by suloku** [comment]
https://github.com/devkitPro/libogc/issues/120
