### ISSUE TITLE
Restoring Save Files to Official NGC Memory Card (Slot A, if it matters)

### ISSUE THREAD

**Issue by turtleisaac1** [suloku/gcmm#32]
So I used this to backup my save files for Pokémon Bank - Ruby &Sapphire to my USB drive. I then plugged said USB drive into my PC (Windows 10, if it helps) and viewed the save file. After editing it in PKHeX, a Pokémon PC Box editor, I saved the file back to the drive with the same name and format. I restored the file on the Memory card with the modified backup, and upon starting up Pokémon Box, it informed me that the save file was corrupt and reloaded the last internal backup, putting me where it was right before editing it. Any ideas on how to do this successfully?

**Comment by turtleisaac1** [comment]
Some additional information: This title was a storage method similar to the modern Pokémon Bank. You would connect your GBA/ GBA SP using a GBA GC Link Cable and move Pokémon from Ruby, Sapphire, Emerald, Fire Red and Leaf Green into the game for storage and exchanging. It also included an additional feature of allowing you to play Ruby and Sapphire on the TV with a GBA GC Link cable without needing a Gameboy Player. (Note: this feature doesn’t work for me.) Also, I am using Nintendont through Homebrew to run it

**Comment by suloku** [comment]
This is an issue regarding pkhex doing something wrong (probably a checksum on the savefile). The restore process works properly or else the whole savegame would be corrupted (it's a 59 block file after all). Try the latest pkhex update.

Also, you might want to setup dolphin (pc gamecube emulator) and do some tests on it, see if it correctly recognizes the savefile after editing if you want to save some time.

Also, try reopening the edited savegame in pkhex and saving the savefile again, it may fix any missing checksums. Also, try searching in pkhex an option to check the checksums, the option is there at least for th NDS/3DS games and should also be for the GBA/gamecube games (I haven't used pkhex with the new supported games).

Here's pkhex issue reports link: https://github.com/kwsch/PKHeX/issues

Also, It's normal that the ruby/saphire gameplay doesn't work on nintendont. It's actually a GBA emulator running on gamecube and that's not properly "emulated" by nintendont (nintendont isn't an emulator).

**Comment by turtleisaac1** [comment]
Ok, I’ve moved my USB drive to my computer again and am trying to open the Box Save File but it says it is an unsupported file type. It worked earlier.

**Comment by turtleisaac1** [comment]
Im trying to use Pokemon Colosseum instead now, and I was able to save the file from PKHeX as the right format and everything. I imported it into Dolphin and the game booted up my save file correctly. Does this mean it will work on the actual GC memory card, or is there something im doing wrong in restoring the file on the memory card from the USB?

**Comment by suloku** [comment]
If it works on dolphin it should work on nintendont.
It seems your box savefile got corrupted at some point, try again.

Also, you can use virtual memory cards on nintendont (raw files) which is the same forman dolphin uses, you don't need an actual gamecube memory card.

**Comment by turtleisaac1** [comment]
Im using an actual gamecube memory card because my wii's graphics are broken. I have the colosseum disk, and i prefer using it on the GC anyway

**Comment by kwsch** [comment]
As stated by @suloku , was because of PKHeX.
https://github.com/kwsch/PKHeX/commit/4778c9c75883bab5fb07a499cec5e8c17340bdf9

You can use a build that was posted prior to 2/19 or compile the latest commit data prior to the next release.
