### ISSUE TITLE
GCMM freeze on gamecube when you press Start to exit. Started with Action Replay.

### ISSUE THREAD

**Issue by Vinnievovi** [suloku/gcmm#34]
GCMM freeze on gamecube when you press Start to exit the homebrew.  Started with Action Replay. To solve it, it would be enough to set the reboot when you press Start to choose boot loader.

**Comment by carstene1ns** [comment]
https://github.com/suloku/gcmm/blob/ba023ef5e73f6798806f76b5f772a49bf500a31d/source/main.c#L862-L863
It already handles the case when pso stub is available, so changing `SYS_RETURNTOMENU` to `SYS_RESTART` should suffice IMO.

**Comment by solderjs** [comment]
What is `SYS_RETURNTOMENU` supposed to do?

I've restored `boot.gci` (which is copied from swiss.gci) onto the memory card, but it's not loading that (which is what loads after the Wind Waker hack loads, when WW is the booting disc).

I have `autoexec.dol` (which is copied from `swiss.dol`) in the root of my SD Gecko, but it's not loading that (which is what is loaded by Action Replay, when AR is the booting disc).

I've put `boot.dol` into the root directory (again, actually `swiss.dol`), but it's not loading that.

What is it expecting to load as the boot loader? Or what is it expecting to yield control to?

**Comment by solderjs** [comment]
It looks like perhaps that needs an `#ifdef` of some sort to return to the Wii menu on Wii, but to reset on GC?

**Comment by suloku** [comment]
You are right, this needs a different case for gamecube and wii (via #ifdef).
SYS_RETURNTOMENU is a quicker way to reboot on wii, for gamecube SYS_RESTART would be needed.

My gc/wii dev is a little rusty, I may try to install latest dev environment and recompile with latest libraries and this change

**Comment by solderjs** [comment]
Do you have some instructions on how to compile it?

I run Mac, but I have a few Linux VPSes, and I run Windows in Parallels and VirtualBox.

Since it has to compile for PowerPC I would imagine that at the very least I need some brief "how to install the toolchain" and "how to cross-compile" instructions.

**Comment by suloku** [comment]
I'll be adding support for sd2sp2, so I'll address this issue too.

**Comment by suloku** [comment]
OK, may you be able to test reboot in gamecube? If this works as intended I'll make the release and push changes to source, thank you for your collaboration!
[gcmm_1.4gbeta2.zip](https://github.com/suloku/gcmm/files/4023705/gcmm_1.4gbeta2.zip)

**Comment by suloku** [comment]
#36 See issue
