### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by KR2004** [suloku/gcmm#39]
The instructions says I should unzip and see an "Apps" folder, but there is no folder called "Apps", just "background", "hbs", and "source".
What am I missing? Should there be updated installation instructions?

**Comment by suloku** [comment]
Seems to me you are not familiar with homebrew, correct me if I am wrong.

Do you want to use the wii version or gamecube version?

For wii I'd recommend this guide to setup homebrew: https://wii.guide/

**Comment by KR2004** [comment]
I'm trying to use GCMM on the Wii.
I've only ever used homebrew for Super Smash M. so I'm not familar with using homebrew outside of that; however, I do already have it set up. 
In particular, I'm looking at this section of the instructions:

------------------------------
Loading / Running the app:
------------------------------

Wii - Via Homebrew Channel:
--------------------
The most popular method of running homebrew on the Wii is through the Homebrew Channel. **_If you already have the channel installed, just copy over the apps folder included in the archive into the root of your SD card._**

If you haven't installed the Homebrew Channel yet, read about how to here:
http://hbc.hackmii.com/

**Comment by suloku** [comment]
Seems this slipped... I' really sorry for the late response, I hope you were able to use GCMM. In any case the problem was you downloaded the source files instead of the actual binary files.

I.E. for the current latest release you need gcmm_1.4f.zip
https://github.com/suloku/gcmm/releases/latest

**Comment by wheaney** [comment]
I'm seeing this on 1.5.2 as well. When I extract [gcmm_1.5.2.zip](https://github.com/suloku/gcmm/releases/download/1.5.2/gcmm_1.5.2.zip), there is no "apps" directory. I extracted the 1.5 zip, and there is an "apps" directory in that one.
