### ISSUE TITLE
GameCube user and gcmm - reboot instructions? 

### ISSUE THREAD

**Issue by Gitomata** [suloku/gcmm#42]
Hi I'm a bit of a noob at this, what is meant by the following in the latest update?

GameCube mode exit sequence:
		1.- If there is a reboot stub (PSOLOAD/SDLOADER), GCMM will return to it
		2.- If not, GCMM will try to load autoexec.dol in fat device used in GCMM
		3.- If not, restart. 

I've got GCloader and gcmm is on the GCloader SD card with an SD Gecko in slot B. Sounds like I can use the no. 2 exit sequence. So do I place swiss as a autoexec.dol file on the GCloader SD card or the SD Gecko card?

Thanks! Sorry I didn't know how to ask this question anywhere else so I have raised it as a issue.

**Comment by suloku** [comment]
In your case you should place autoexec.dol in sd gecko.

GCMM doesn't support gcloader's sd card.

**Comment by Gitomata** [comment]
Thanks for confirming :)

**Comment by suloku** [comment]
@Gitomata as of 1.5.2 GCloader is supported by GCMM in case you are interested.

**Comment by Gitomata** [comment]
@suloku Thanks for the heads up, will give it a go.
