### ISSUE TITLE
SD2SP2 not working on version 15

### ISSUE THREAD

**Issue by f3bandit** [suloku/gcmm#43]
SD2SP2 is detected perfectly in version 14g beta 2 and 14g beta 3.
can backup and restore game saves and restore no problem.
version 15 does not detect SD2SP2 at all.
thx :)

**Comment by Extrems** [comment]
The official repository for this fork is now https://github.com/extremscorner/libogc2.
You'll also need https://github.com/extremscorner/libfat. See extremscorner/gamecube-examples@0c92030198f6cbc540d941cc4243abd0dcedc5f8 for a migration example.

**Comment by suloku** [comment]
Thank you very much. By the way, I've been checking card.c and this is missing:
https://github.com/devkitPro/libogc/issues/113

I made a pull request already.

**Comment by suloku** [comment]
@f3bandit finally it's working fine on my end, thanks to Extrems's pointers.

Besides SD2SP2 working and using Extrems's updated libfat, there's also a fix Extrems implemented in libogc2 in january in card.c, current device is now shown on screen (below version number) and the boot secuence has been updated.

I've also added some command line arguments to use with swiss to make it easier to use if one prefers using sdgecko over sd2sp2 for storage (in case someone uses both). I've included a txt with detailed information.

Please try this version @f3bandit:
[gcmm1.5.1beta1.zip](https://github.com/suloku/gcmm/files/7354252/gcmm1.5.1beta1.zip)

**Comment by f3bandit** [comment]
@suloku anyway way we can add darkmode while we are at it
![background](https://user-images.githubusercontent.com/4943324/137603695-3b35eb42-82a5-44fc-9781-768695a55397.png)
?

**Comment by f3bandit** [comment]
> I've seen the changes on libogc2, there seeems to have been lots of loose ends still there. About gcloader support, I don't see any reason not to add it, besides not owning one so I won't be able to test. If someone is willing to test I'll work on it. Also, it seems I should code some kind of device selection screen. I'll dig into how swiss detects an sd gecko being inserted, as the only method I can think of right now is trying to mount both memcard slots and asume that wrong device error will be an sd gecko.
> 
> Also, dark theme seems like a great idea, I'll test your designs, they look fantastic. If you still have the psd would you mind sending it to [sulokutdcmago@gmail.com](mailto:sulokutdcmago@gmail.com)?

does the compiler use the psd instead of the bmp files? as I only used parts of the psd to extract layers from and import into paint.net

**Comment by suloku** [comment]
Thank you, it was so it can be added to source if future editong is needed

**Comment by f3bandit** [comment]
> Thank you, it was so it can be added to source if future editong is needed

No problem,
I updated all the images. just extract and copy and ovewrite all orighinal files! :)
[gcmm-master_darkmode.zip](https://github.com/suloku/gcmm/files/7360666/gcmm-master_darkmode.zip)
m

**Comment by f3bandit** [comment]
I forked your git and updated the fork with the new images, and created a pull request. :)

**Comment by f3bandit** [comment]
looks amazing and works great, thank you so much! you are a god among men :)
